<?xml version='1.0'?>
<robot name ='red_cube' xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="side_len" value="0.01" />

<link name="cube">
  <collision>
    <origin xyz="0 0 ${side_len/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${side_len} ${side_len} ${side_len}" />
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${side_len/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${side_len} ${side_len} ${side_len}" />
    </geometry>
  </visual>

  <inertial>
    <origin xyz="0 0 ${side_len/2}" rpy="0 0 0" />
    <mass value="0.05" />
    <inertia
      ixx="0.001" ixy="0.0"  ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001" />
  </inertial>
  </link>

<gazebo reference="cube">
  <material>Gazebo/Red</material>
    <mu1>5</mu1>
    <mu2>5</mu2>
</gazebo>

</robot>
