<?xml version='1.0'?>
<robot name ='workspace' xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="width1" value="0.11" />
<xacro:property name="width2" value="0.11" />
<xacro:property name="height1" value="0.03" />
<xacro:property name="height2" value="0.002" />


<link name="world"/>

<joint name = "joint_fix" type = "fixed">
  <parent link="world"/>
  <child link = "bottom"/>
</joint>

<link name ="bottom"> <!--2-->
  <collision>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width1} ${width2} ${height2}"/> <!--3-->
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width1} ${width2} ${height2}"/>
    </geometry>
  </visual>

  <inertial>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0" />
    <mass value="0.05" />
    <inertia
      ixx="0.001" ixy="0.0"  ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001" />
  </inertial>
</link>

<joint name = "left_wall" type = "fixed">
  <parent link="bottom"/>
  <child link = "left"/>
</joint>


<link name = "left">
  <collision> <!--4-->
    <origin xyz="-${width1/2} 0 ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${height2} ${width2} ${height1}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="-${width1/2} 0 ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${height2} ${width2} ${height1}"/>
    </geometry>
  </visual>

  <inertial>
    <origin xyz="-${width1/2} 0 ${height1/2}" rpy="0 0 0" />
    <mass value="0.05" />
    <inertia
      ixx="0.001" ixy="0.0"  ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001" />
  </inertial>
</link>

<joint name = "right_wall" type = "fixed">
  <parent link="bottom"/>
  <child link = "right"/>
</joint>

<link name="right">
  <collision>
    <origin xyz="${width1/2} 0 ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${height2} ${width2} ${height1}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="${width1/2} 0 ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${height2} ${width2} ${height1}"/>
    </geometry>
  </visual>

  <inertial>
    <origin xyz="${width1/2} 0 ${height1/2}" rpy="0 0 0" />
    <mass value="0.05" />
    <inertia
      ixx="0.001" ixy="0.0"  ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001" />
  </inertial>
</link>

<joint name = "back_wall" type = "fixed">
  <parent link="bottom"/>
  <child link = "back"/>
</joint>

<link name="back">
  <collision>
    <origin xyz="0 ${width1/2} ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width1} ${height2} ${height1}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 ${width1/2} ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width1} ${height2} ${height1}"/>
    </geometry>
  </visual>

  <inertial>
    <origin xyz="0 ${width1/2} ${height1/2}" rpy="0 0 0" />
    <mass value="0.05" />
    <inertia
      ixx="0.001" ixy="0.0"  ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001" />
  </inertial>
</link>

<joint name = "front_wall" type = "fixed">
  <parent link="bottom"/>
  <child link = "front"/>
</joint>

<link name="front">
  <collision>
    <origin xyz="0 -${width1/2} ${height1/2}" rpy= "0 0 0"/>
    <geometry>
      <box size="${width1} ${height2} ${height1}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 -${width1/2} ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width1} ${height2} ${height1}"/>
    </geometry>
  </visual>

  <inertial>
    <origin xyz="0 -${width1/2} ${height1/2}" rpy="0 0 0"/>
    <mass value="0.05" />
    <inertia
      ixx="0.001" ixy="0.0"  ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001" />
  </inertial>
</link>

<gazebo reference="bottom">
  <mu1>10</mu1>
  <mu2>10</mu2>
  <material>Gazebo/White</material>
  <static>true</static>
  <maxVel>0</maxVel>
  <minDepth>0.001</minDepth>
</gazebo>

<gazebo reference="right">
  <mu1>10</mu1>
  <mu2>10</mu2>
  <material>Gazebo/White</material>
  <static>true</static>
  <maxVel>0</maxVel>
  <minDepth>0.001</minDepth>
</gazebo>

<gazebo reference="left">
  <mu1>10</mu1>
  <mu2>10</mu2>
  <material>Gazebo/White</material>
  <static>true</static>
  <maxVel>0</maxVel>
  <minDepth>0.001</minDepth>
</gazebo>

<gazebo reference="back">
  <mu1>10</mu1>
  <mu2>10</mu2>
  <material>Gazebo/White</material>
  <static>true</static>
  <maxVel>0</maxVel>
  <minDepth>0.001</minDepth>
</gazebo>

<gazebo reference="front">
  <mu1>10</mu1>
  <mu2>10</mu2>
  <material>Gazebo/White</material>
</gazebo>

</robot>
